// Generated by @opencode-ai/httpapi-codegen. Do not edit.
import { Effect, Stream, Schema } from "effect"
import { Sse } from "effect/unstable/encoding"
import { HttpClientError } from "effect/unstable/http"
import { HttpApiClient } from "effect/unstable/httpapi"
import { ClientApi } from "../contract"
import { ClientError } from "./client-error"

type RawClient = HttpApiClient.ForApi<typeof ClientApi>

const mapClientError = <E>(error: E) =>
  HttpClientError.isHttpClientError(error) || Schema.isSchemaError(error) || Sse.Retry.is(error)
    ? new ClientError({ cause: error })
    : error

const Endpoint0_0 = (raw: RawClient["server.health"]) => () =>
  raw["health.get"]({}).pipe(Effect.mapError(mapClientError))

const adaptGroup0 = (raw: RawClient["server.health"]) => ({ get: Endpoint0_0(raw) })

const Endpoint1_0 = (raw: RawClient["server.issueWatcher"]) => () =>
  raw["issueWatcher.sources"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint1_1Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.verifySource"]>[0]
type Endpoint1_1Input = {
  readonly integrationID: Endpoint1_1Request["params"]["integrationID"]
  readonly key?: Endpoint1_1Request["payload"]["key"]
  readonly inputs: Endpoint1_1Request["payload"]["inputs"]
  readonly useSavedConnection?: Endpoint1_1Request["payload"]["useSavedConnection"]
}
const Endpoint1_1 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_1Input) =>
  raw["issueWatcher.verifySource"]({
    params: { integrationID: input["integrationID"] },
    payload: { key: input["key"], inputs: input["inputs"], useSavedConnection: input["useSavedConnection"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_2Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.createConnection"]>[0]
type Endpoint1_2Input = {
  readonly integrationID: Endpoint1_2Request["params"]["integrationID"]
  readonly key: Endpoint1_2Request["payload"]["key"]
  readonly inputs: Endpoint1_2Request["payload"]["inputs"]
  readonly label?: Endpoint1_2Request["payload"]["label"]
}
const Endpoint1_2 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_2Input) =>
  raw["issueWatcher.createConnection"]({
    params: { integrationID: input["integrationID"] },
    payload: { key: input["key"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_3Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.rotateConnection"]>[0]
type Endpoint1_3Input = {
  readonly integrationID: Endpoint1_3Request["params"]["integrationID"]
  readonly connectionID: Endpoint1_3Request["params"]["connectionID"]
  readonly key?: Endpoint1_3Request["payload"]["key"]
  readonly inputs: Endpoint1_3Request["payload"]["inputs"]
  readonly label?: Endpoint1_3Request["payload"]["label"]
}
const Endpoint1_3 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_3Input) =>
  raw["issueWatcher.rotateConnection"]({
    params: { integrationID: input["integrationID"], connectionID: input["connectionID"] },
    payload: { key: input["key"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_4Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.metadata"]>[0]
type Endpoint1_4Input = {
  readonly integrationID: Endpoint1_4Request["params"]["integrationID"]
  readonly connectionID: Endpoint1_4Request["params"]["connectionID"]
  readonly issueProjects: Endpoint1_4Request["payload"]["issueProjects"]
}
const Endpoint1_4 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_4Input) =>
  raw["issueWatcher.metadata"]({
    params: { integrationID: input["integrationID"], connectionID: input["connectionID"] },
    payload: { issueProjects: input["issueProjects"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_5Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.syncMetadata"]>[0]
type Endpoint1_5Input = {
  readonly integrationID: Endpoint1_5Request["params"]["integrationID"]
  readonly connectionID: Endpoint1_5Request["params"]["connectionID"]
}
const Endpoint1_5 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_5Input) =>
  raw["issueWatcher.syncMetadata"]({
    params: { integrationID: input["integrationID"], connectionID: input["connectionID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_6Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.preview"]>[0]
type Endpoint1_6Input = {
  readonly integrationID: Endpoint1_6Request["payload"]["integrationID"]
  readonly connectionID: Endpoint1_6Request["payload"]["connectionID"]
  readonly criteria: Endpoint1_6Request["payload"]["criteria"]
  readonly routing: Endpoint1_6Request["payload"]["routing"]
  readonly action: Endpoint1_6Request["payload"]["action"]
}
const Endpoint1_6 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_6Input) =>
  raw["issueWatcher.preview"]({
    payload: {
      integrationID: input["integrationID"],
      connectionID: input["connectionID"],
      criteria: input["criteria"],
      routing: input["routing"],
      action: input["action"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint1_7 = (raw: RawClient["server.issueWatcher"]) => () =>
  raw["issueWatcher.getSettings"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint1_8Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.updateSettings"]>[0]
type Endpoint1_8Input = {
  readonly pollInterval: Endpoint1_8Request["payload"]["pollInterval"]
  readonly concurrentRuns: Endpoint1_8Request["payload"]["concurrentRuns"]
  readonly retryFailedRuns: Endpoint1_8Request["payload"]["retryFailedRuns"]
}
const Endpoint1_8 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_8Input) =>
  raw["issueWatcher.updateSettings"]({
    payload: {
      pollInterval: input["pollInterval"],
      concurrentRuns: input["concurrentRuns"],
      retryFailedRuns: input["retryFailedRuns"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint1_9 = (raw: RawClient["server.issueWatcher"]) => () =>
  raw["issueWatcher.list"]({}).pipe(Effect.mapError(mapClientError))

const Endpoint1_10 = (raw: RawClient["server.issueWatcher"]) => () =>
  raw["issueWatcher.runAll"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint1_11Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.create"]>[0]
type Endpoint1_11Input = {
  readonly integrationID: Endpoint1_11Request["payload"]["integrationID"]
  readonly connectionID: Endpoint1_11Request["payload"]["connectionID"]
  readonly name: Endpoint1_11Request["payload"]["name"]
  readonly enabled?: Endpoint1_11Request["payload"]["enabled"]
  readonly projectID?: Endpoint1_11Request["payload"]["projectID"]
  readonly criteria: Endpoint1_11Request["payload"]["criteria"]
  readonly routing: Endpoint1_11Request["payload"]["routing"]
  readonly action: Endpoint1_11Request["payload"]["action"]
}
const Endpoint1_11 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_11Input) =>
  raw["issueWatcher.create"]({
    payload: {
      integrationID: input["integrationID"],
      connectionID: input["connectionID"],
      name: input["name"],
      enabled: input["enabled"],
      projectID: input["projectID"],
      criteria: input["criteria"],
      routing: input["routing"],
      action: input["action"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_12Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.get"]>[0]
type Endpoint1_12Input = { readonly watcherID: Endpoint1_12Request["params"]["watcherID"] }
const Endpoint1_12 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_12Input) =>
  raw["issueWatcher.get"]({ params: { watcherID: input["watcherID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_13Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.update"]>[0]
type Endpoint1_13Input = {
  readonly watcherID: Endpoint1_13Request["params"]["watcherID"]
  readonly name?: Endpoint1_13Request["payload"]["name"]
  readonly projectID?: Endpoint1_13Request["payload"]["projectID"]
  readonly criteria?: Endpoint1_13Request["payload"]["criteria"]
  readonly routing?: Endpoint1_13Request["payload"]["routing"]
  readonly action?: Endpoint1_13Request["payload"]["action"]
  readonly integrationID?: Endpoint1_13Request["payload"]["integrationID"]
  readonly connectionID?: Endpoint1_13Request["payload"]["connectionID"]
}
const Endpoint1_13 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_13Input) =>
  raw["issueWatcher.update"]({
    params: { watcherID: input["watcherID"] },
    payload: {
      name: input["name"],
      projectID: input["projectID"],
      criteria: input["criteria"],
      routing: input["routing"],
      action: input["action"],
      integrationID: input["integrationID"],
      connectionID: input["connectionID"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_14Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.archive"]>[0]
type Endpoint1_14Input = { readonly watcherID: Endpoint1_14Request["params"]["watcherID"] }
const Endpoint1_14 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_14Input) =>
  raw["issueWatcher.archive"]({ params: { watcherID: input["watcherID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_15Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.run"]>[0]
type Endpoint1_15Input = { readonly watcherID: Endpoint1_15Request["params"]["watcherID"] }
const Endpoint1_15 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_15Input) =>
  raw["issueWatcher.run"]({ params: { watcherID: input["watcherID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_16Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.history"]>[0]
type Endpoint1_16Input = {
  readonly watcherID: Endpoint1_16Request["params"]["watcherID"]
  readonly cursor?: Endpoint1_16Request["query"]["cursor"]
  readonly limit?: Endpoint1_16Request["query"]["limit"]
}
const Endpoint1_16 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_16Input) =>
  raw["issueWatcher.history"]({
    params: { watcherID: input["watcherID"] },
    query: { cursor: input["cursor"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_17Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.ignores"]>[0]
type Endpoint1_17Input = { readonly watcherID: Endpoint1_17Request["params"]["watcherID"] }
const Endpoint1_17 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_17Input) =>
  raw["issueWatcher.ignores"]({ params: { watcherID: input["watcherID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_18Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.inbox"]>[0]
type Endpoint1_18Input = {
  readonly cursor?: Endpoint1_18Request["query"]["cursor"]
  readonly limit?: Endpoint1_18Request["query"]["limit"]
  readonly state?: Endpoint1_18Request["query"]["state"]
  readonly integrationID?: Endpoint1_18Request["query"]["integrationID"]
  readonly filter?: Endpoint1_18Request["query"]["filter"]
}
const Endpoint1_18 = (raw: RawClient["server.issueWatcher"]) => (input?: Endpoint1_18Input) =>
  raw["issueWatcher.inbox"]({
    query: {
      cursor: input?.["cursor"],
      limit: input?.["limit"],
      state: input?.["state"],
      integrationID: input?.["integrationID"],
      filter: input?.["filter"],
    },
  }).pipe(Effect.mapError(mapClientError))

const Endpoint1_19 = (raw: RawClient["server.issueWatcher"]) => () =>
  raw["issueWatcher.inboxSummary"]({}).pipe(Effect.mapError(mapClientError))

type Endpoint1_20Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.bulk"]>[0]
type Endpoint1_20Input = {
  readonly matchIDs: Endpoint1_20Request["payload"]["matchIDs"]
  readonly action: Endpoint1_20Request["payload"]["action"]
  readonly mode?: Endpoint1_20Request["payload"]["mode"]
}
const Endpoint1_20 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_20Input) =>
  raw["issueWatcher.bulk"]({
    payload: { matchIDs: input["matchIDs"], action: input["action"], mode: input["mode"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_21Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.approve"]>[0]
type Endpoint1_21Input = {
  readonly matchID: Endpoint1_21Request["params"]["matchID"]
  readonly mode: Endpoint1_21Request["payload"]["mode"]
  readonly projectID?: Endpoint1_21Request["payload"]["projectID"]
  readonly workspace?: Endpoint1_21Request["payload"]["workspace"]
}
const Endpoint1_21 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_21Input) =>
  raw["issueWatcher.approve"]({
    params: { matchID: input["matchID"] },
    payload: { mode: input["mode"], projectID: input["projectID"], workspace: input["workspace"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_22Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.routeMatch"]>[0]
type Endpoint1_22Input = {
  readonly matchID: Endpoint1_22Request["params"]["matchID"]
  readonly projectID: Endpoint1_22Request["payload"]["projectID"]
  readonly persistMapping?: Endpoint1_22Request["payload"]["persistMapping"]
}
const Endpoint1_22 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_22Input) =>
  raw["issueWatcher.routeMatch"]({
    params: { matchID: input["matchID"] },
    payload: { projectID: input["projectID"], persistMapping: input["persistMapping"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_23Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.skip"]>[0]
type Endpoint1_23Input = { readonly matchID: Endpoint1_23Request["params"]["matchID"] }
const Endpoint1_23 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_23Input) =>
  raw["issueWatcher.skip"]({ params: { matchID: input["matchID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_24Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.dismiss"]>[0]
type Endpoint1_24Input = { readonly matchID: Endpoint1_24Request["params"]["matchID"] }
const Endpoint1_24 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_24Input) =>
  raw["issueWatcher.dismiss"]({ params: { matchID: input["matchID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_25Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.rematerialize"]>[0]
type Endpoint1_25Input = {
  readonly matchID: Endpoint1_25Request["params"]["matchID"]
  readonly mode: Endpoint1_25Request["payload"]["mode"]
  readonly projectID?: Endpoint1_25Request["payload"]["projectID"]
  readonly workspace?: Endpoint1_25Request["payload"]["workspace"]
}
const Endpoint1_25 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_25Input) =>
  raw["issueWatcher.rematerialize"]({
    params: { matchID: input["matchID"] },
    payload: { mode: input["mode"], projectID: input["projectID"], workspace: input["workspace"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_26Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.duplicateDetail"]>[0]
type Endpoint1_26Input = { readonly matchID: Endpoint1_26Request["params"]["matchID"] }
const Endpoint1_26 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_26Input) =>
  raw["issueWatcher.duplicateDetail"]({ params: { matchID: input["matchID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint1_27Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.resolveDuplicate"]>[0]
type Endpoint1_27Input = {
  readonly matchID: Endpoint1_27Request["params"]["matchID"]
  readonly action: Endpoint1_27Request["payload"]["action"]
  readonly mode?: Endpoint1_27Request["payload"]["mode"]
  readonly projectID?: Endpoint1_27Request["payload"]["projectID"]
  readonly workspace?: Endpoint1_27Request["payload"]["workspace"]
}
const Endpoint1_27 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_27Input) =>
  raw["issueWatcher.resolveDuplicate"]({
    params: { matchID: input["matchID"] },
    payload: {
      action: input["action"],
      mode: input["mode"],
      projectID: input["projectID"],
      workspace: input["workspace"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_28Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.addIgnore"]>[0]
type Endpoint1_28Input = {
  readonly watcherID: Endpoint1_28Request["params"]["watcherID"]
  readonly externalID: Endpoint1_28Request["payload"]["externalID"]
  readonly reason?: Endpoint1_28Request["payload"]["reason"]
}
const Endpoint1_28 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_28Input) =>
  raw["issueWatcher.addIgnore"]({
    params: { watcherID: input["watcherID"] },
    payload: { externalID: input["externalID"], reason: input["reason"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint1_29Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.removeIgnore"]>[0]
type Endpoint1_29Input = {
  readonly watcherID: Endpoint1_29Request["params"]["watcherID"]
  readonly externalID: Endpoint1_29Request["params"]["externalID"]
}
const Endpoint1_29 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_29Input) =>
  raw["issueWatcher.removeIgnore"]({ params: { watcherID: input["watcherID"], externalID: input["externalID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint1_30Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.provenanceDetail"]>[0]
type Endpoint1_30Input = { readonly sessionID: Endpoint1_30Request["params"]["sessionID"] }
const Endpoint1_30 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_30Input) =>
  raw["issueWatcher.provenanceDetail"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint1_31Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.syncProvenance"]>[0]
type Endpoint1_31Input = { readonly sessionID: Endpoint1_31Request["params"]["sessionID"] }
const Endpoint1_31 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_31Input) =>
  raw["issueWatcher.syncProvenance"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint1_32Request = Parameters<RawClient["server.issueWatcher"]["issueWatcher.enable"]>[0]
type Endpoint1_32Input = {
  readonly watcherID: Endpoint1_32Request["params"]["watcherID"]
  readonly enabled: Endpoint1_32Request["payload"]["enabled"]
}
const Endpoint1_32 = (raw: RawClient["server.issueWatcher"]) => (input: Endpoint1_32Input) =>
  raw["issueWatcher.enable"]({
    params: { watcherID: input["watcherID"] },
    payload: { enabled: input["enabled"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup1 = (raw: RawClient["server.issueWatcher"]) => ({
  sources: Endpoint1_0(raw),
  verifySource: Endpoint1_1(raw),
  createConnection: Endpoint1_2(raw),
  rotateConnection: Endpoint1_3(raw),
  metadata: Endpoint1_4(raw),
  syncMetadata: Endpoint1_5(raw),
  preview: Endpoint1_6(raw),
  getSettings: Endpoint1_7(raw),
  updateSettings: Endpoint1_8(raw),
  list: Endpoint1_9(raw),
  runAll: Endpoint1_10(raw),
  create: Endpoint1_11(raw),
  get: Endpoint1_12(raw),
  update: Endpoint1_13(raw),
  archive: Endpoint1_14(raw),
  run: Endpoint1_15(raw),
  history: Endpoint1_16(raw),
  ignores: Endpoint1_17(raw),
  inbox: Endpoint1_18(raw),
  inboxSummary: Endpoint1_19(raw),
  bulk: Endpoint1_20(raw),
  approve: Endpoint1_21(raw),
  routeMatch: Endpoint1_22(raw),
  skip: Endpoint1_23(raw),
  dismiss: Endpoint1_24(raw),
  rematerialize: Endpoint1_25(raw),
  duplicateDetail: Endpoint1_26(raw),
  resolveDuplicate: Endpoint1_27(raw),
  addIgnore: Endpoint1_28(raw),
  removeIgnore: Endpoint1_29(raw),
  provenanceDetail: Endpoint1_30(raw),
  syncProvenance: Endpoint1_31(raw),
  enable: Endpoint1_32(raw),
})

type Endpoint2_0Request = Parameters<RawClient["server.location"]["location.get"]>[0]
type Endpoint2_0Input = { readonly location?: Endpoint2_0Request["query"]["location"] }
const Endpoint2_0 = (raw: RawClient["server.location"]) => (input?: Endpoint2_0Input) =>
  raw["location.get"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup2 = (raw: RawClient["server.location"]) => ({ get: Endpoint2_0(raw) })

type Endpoint3_0Request = Parameters<RawClient["server.agent"]["agent.list"]>[0]
type Endpoint3_0Input = { readonly location?: Endpoint3_0Request["query"]["location"] }
const Endpoint3_0 = (raw: RawClient["server.agent"]) => (input?: Endpoint3_0Input) =>
  raw["agent.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup3 = (raw: RawClient["server.agent"]) => ({ list: Endpoint3_0(raw) })

type Endpoint4_0Request = Parameters<RawClient["server.session"]["session.list"]>[0]
type Endpoint4_0Input = {
  readonly workspace?: Endpoint4_0Request["query"]["workspace"]
  readonly limit?: Endpoint4_0Request["query"]["limit"]
  readonly order?: Endpoint4_0Request["query"]["order"]
  readonly search?: Endpoint4_0Request["query"]["search"]
  readonly directory?: Endpoint4_0Request["query"]["directory"]
  readonly project?: Endpoint4_0Request["query"]["project"]
  readonly subpath?: Endpoint4_0Request["query"]["subpath"]
  readonly cursor?: Endpoint4_0Request["query"]["cursor"]
}
const Endpoint4_0 = (raw: RawClient["server.session"]) => (input?: Endpoint4_0Input) =>
  raw["session.list"]({
    query: {
      workspace: input?.["workspace"],
      limit: input?.["limit"],
      order: input?.["order"],
      search: input?.["search"],
      directory: input?.["directory"],
      project: input?.["project"],
      subpath: input?.["subpath"],
      cursor: input?.["cursor"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_1Request = Parameters<RawClient["server.session"]["session.create"]>[0]
type Endpoint4_1Input = {
  readonly id?: Endpoint4_1Request["payload"]["id"]
  readonly agent?: Endpoint4_1Request["payload"]["agent"]
  readonly model?: Endpoint4_1Request["payload"]["model"]
  readonly location?: Endpoint4_1Request["payload"]["location"]
}
const Endpoint4_1 = (raw: RawClient["server.session"]) => (input?: Endpoint4_1Input) =>
  raw["session.create"]({
    payload: { id: input?.["id"], agent: input?.["agent"], model: input?.["model"], location: input?.["location"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const Endpoint4_2 = (raw: RawClient["server.session"]) => () =>
  raw["session.active"]({}).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_3Request = Parameters<RawClient["server.session"]["session.get"]>[0]
type Endpoint4_3Input = { readonly sessionID: Endpoint4_3Request["params"]["sessionID"] }
const Endpoint4_3 = (raw: RawClient["server.session"]) => (input: Endpoint4_3Input) =>
  raw["session.get"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_4Request = Parameters<RawClient["server.session"]["session.switchAgent"]>[0]
type Endpoint4_4Input = {
  readonly sessionID: Endpoint4_4Request["params"]["sessionID"]
  readonly agent: Endpoint4_4Request["payload"]["agent"]
}
const Endpoint4_4 = (raw: RawClient["server.session"]) => (input: Endpoint4_4Input) =>
  raw["session.switchAgent"]({ params: { sessionID: input["sessionID"] }, payload: { agent: input["agent"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_5Request = Parameters<RawClient["server.session"]["session.switchModel"]>[0]
type Endpoint4_5Input = {
  readonly sessionID: Endpoint4_5Request["params"]["sessionID"]
  readonly model: Endpoint4_5Request["payload"]["model"]
}
const Endpoint4_5 = (raw: RawClient["server.session"]) => (input: Endpoint4_5Input) =>
  raw["session.switchModel"]({ params: { sessionID: input["sessionID"] }, payload: { model: input["model"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_6Request = Parameters<RawClient["server.session"]["session.prompt"]>[0]
type Endpoint4_6Input = {
  readonly sessionID: Endpoint4_6Request["params"]["sessionID"]
  readonly id?: Endpoint4_6Request["payload"]["id"]
  readonly prompt: Endpoint4_6Request["payload"]["prompt"]
  readonly delivery?: Endpoint4_6Request["payload"]["delivery"]
  readonly resume?: Endpoint4_6Request["payload"]["resume"]
}
const Endpoint4_6 = (raw: RawClient["server.session"]) => (input: Endpoint4_6Input) =>
  raw["session.prompt"]({
    params: { sessionID: input["sessionID"] },
    payload: { id: input["id"], prompt: input["prompt"], delivery: input["delivery"], resume: input["resume"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_7Request = Parameters<RawClient["server.session"]["session.input.pending"]>[0]
type Endpoint4_7Input = { readonly sessionID: Endpoint4_7Request["params"]["sessionID"] }
const Endpoint4_7 = (raw: RawClient["server.session"]) => (input: Endpoint4_7Input) =>
  raw["session.input.pending"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_8Request = Parameters<RawClient["server.session"]["session.input.replace"]>[0]
type Endpoint4_8Input = {
  readonly sessionID: Endpoint4_8Request["params"]["sessionID"]
  readonly messageID: Endpoint4_8Request["params"]["messageID"]
  readonly prompt: Endpoint4_8Request["payload"]["prompt"]
}
const Endpoint4_8 = (raw: RawClient["server.session"]) => (input: Endpoint4_8Input) =>
  raw["session.input.replace"]({
    params: { sessionID: input["sessionID"], messageID: input["messageID"] },
    payload: { prompt: input["prompt"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_9Request = Parameters<RawClient["server.session"]["session.input.cancel"]>[0]
type Endpoint4_9Input = {
  readonly sessionID: Endpoint4_9Request["params"]["sessionID"]
  readonly messageID: Endpoint4_9Request["params"]["messageID"]
}
const Endpoint4_9 = (raw: RawClient["server.session"]) => (input: Endpoint4_9Input) =>
  raw["session.input.cancel"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint4_10Request = Parameters<RawClient["server.session"]["session.resume.confirm"]>[0]
type Endpoint4_10Input = {
  readonly sessionID: Endpoint4_10Request["params"]["sessionID"]
  readonly attemptID: Endpoint4_10Request["payload"]["attemptID"]
  readonly newAttemptID: Endpoint4_10Request["payload"]["newAttemptID"]
}
const Endpoint4_10 = (raw: RawClient["server.session"]) => (input: Endpoint4_10Input) =>
  raw["session.resume.confirm"]({
    params: { sessionID: input["sessionID"] },
    payload: { attemptID: input["attemptID"], newAttemptID: input["newAttemptID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_11Request = Parameters<RawClient["server.session"]["session.resume"]>[0]
type Endpoint4_11Input = {
  readonly sessionID: Endpoint4_11Request["params"]["sessionID"]
  readonly expectedMessageID: Endpoint4_11Request["payload"]["expectedMessageID"]
  readonly attemptID?: Endpoint4_11Request["payload"]["attemptID"]
}
const Endpoint4_11 = (raw: RawClient["server.session"]) => (input: Endpoint4_11Input) =>
  raw["session.resume"]({
    params: { sessionID: input["sessionID"] },
    payload: { expectedMessageID: input["expectedMessageID"], attemptID: input["attemptID"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_12Request = Parameters<RawClient["server.session"]["session.compact"]>[0]
type Endpoint4_12Input = { readonly sessionID: Endpoint4_12Request["params"]["sessionID"] }
const Endpoint4_12 = (raw: RawClient["server.session"]) => (input: Endpoint4_12Input) =>
  raw["session.compact"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_13Request = Parameters<RawClient["server.session"]["session.wait"]>[0]
type Endpoint4_13Input = { readonly sessionID: Endpoint4_13Request["params"]["sessionID"] }
const Endpoint4_13 = (raw: RawClient["server.session"]) => (input: Endpoint4_13Input) =>
  raw["session.wait"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_14Request = Parameters<RawClient["server.session"]["session.revert.stage"]>[0]
type Endpoint4_14Input = {
  readonly sessionID: Endpoint4_14Request["params"]["sessionID"]
  readonly messageID: Endpoint4_14Request["payload"]["messageID"]
  readonly files?: Endpoint4_14Request["payload"]["files"]
}
const Endpoint4_14 = (raw: RawClient["server.session"]) => (input: Endpoint4_14Input) =>
  raw["session.revert.stage"]({
    params: { sessionID: input["sessionID"] },
    payload: { messageID: input["messageID"], files: input["files"] },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_15Request = Parameters<RawClient["server.session"]["session.revert.clear"]>[0]
type Endpoint4_15Input = { readonly sessionID: Endpoint4_15Request["params"]["sessionID"] }
const Endpoint4_15 = (raw: RawClient["server.session"]) => (input: Endpoint4_15Input) =>
  raw["session.revert.clear"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_16Request = Parameters<RawClient["server.session"]["session.revert.commit"]>[0]
type Endpoint4_16Input = { readonly sessionID: Endpoint4_16Request["params"]["sessionID"] }
const Endpoint4_16 = (raw: RawClient["server.session"]) => (input: Endpoint4_16Input) =>
  raw["session.revert.commit"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_17Request = Parameters<RawClient["server.session"]["session.context"]>[0]
type Endpoint4_17Input = { readonly sessionID: Endpoint4_17Request["params"]["sessionID"] }
const Endpoint4_17 = (raw: RawClient["server.session"]) => (input: Endpoint4_17Input) =>
  raw["session.context"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint4_18Request = Parameters<RawClient["server.session"]["session.history"]>[0]
type Endpoint4_18Input = {
  readonly sessionID: Endpoint4_18Request["params"]["sessionID"]
  readonly limit?: Endpoint4_18Request["query"]["limit"]
  readonly after?: Endpoint4_18Request["query"]["after"]
}
const Endpoint4_18 = (raw: RawClient["server.session"]) => (input: Endpoint4_18Input) =>
  raw["session.history"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], after: input["after"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint4_19Request = Parameters<RawClient["server.session"]["session.events"]>[0]
type Endpoint4_19Input = {
  readonly sessionID: Endpoint4_19Request["params"]["sessionID"]
  readonly after?: Endpoint4_19Request["query"]["after"]
}
const Endpoint4_19 = (raw: RawClient["server.session"]) => (input: Endpoint4_19Input) =>
  Stream.unwrap(
    raw["session.events"]({ params: { sessionID: input["sessionID"] }, query: { after: input["after"] } }).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

type Endpoint4_20Request = Parameters<RawClient["server.session"]["session.interrupt"]>[0]
type Endpoint4_20Input = { readonly sessionID: Endpoint4_20Request["params"]["sessionID"] }
const Endpoint4_20 = (raw: RawClient["server.session"]) => (input: Endpoint4_20Input) =>
  raw["session.interrupt"]({ params: { sessionID: input["sessionID"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint4_21Request = Parameters<RawClient["server.session"]["session.message"]>[0]
type Endpoint4_21Input = {
  readonly sessionID: Endpoint4_21Request["params"]["sessionID"]
  readonly messageID: Endpoint4_21Request["params"]["messageID"]
}
const Endpoint4_21 = (raw: RawClient["server.session"]) => (input: Endpoint4_21Input) =>
  raw["session.message"]({ params: { sessionID: input["sessionID"], messageID: input["messageID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

const adaptGroup4 = (raw: RawClient["server.session"]) => ({
  list: Endpoint4_0(raw),
  create: Endpoint4_1(raw),
  active: Endpoint4_2(raw),
  get: Endpoint4_3(raw),
  switchAgent: Endpoint4_4(raw),
  switchModel: Endpoint4_5(raw),
  prompt: Endpoint4_6(raw),
  pending: Endpoint4_7(raw),
  replace: Endpoint4_8(raw),
  cancel: Endpoint4_9(raw),
  confirm: Endpoint4_10(raw),
  resume: Endpoint4_11(raw),
  compact: Endpoint4_12(raw),
  wait: Endpoint4_13(raw),
  stage: Endpoint4_14(raw),
  clear: Endpoint4_15(raw),
  commit: Endpoint4_16(raw),
  context: Endpoint4_17(raw),
  history: Endpoint4_18(raw),
  events: Endpoint4_19(raw),
  interrupt: Endpoint4_20(raw),
  message: Endpoint4_21(raw),
})

type Endpoint5_0Request = Parameters<RawClient["server.message"]["session.messages"]>[0]
type Endpoint5_0Input = {
  readonly sessionID: Endpoint5_0Request["params"]["sessionID"]
  readonly limit?: Endpoint5_0Request["query"]["limit"]
  readonly order?: Endpoint5_0Request["query"]["order"]
  readonly cursor?: Endpoint5_0Request["query"]["cursor"]
}
const Endpoint5_0 = (raw: RawClient["server.message"]) => (input: Endpoint5_0Input) =>
  raw["session.messages"]({
    params: { sessionID: input["sessionID"] },
    query: { limit: input["limit"], order: input["order"], cursor: input["cursor"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup5 = (raw: RawClient["server.message"]) => ({ list: Endpoint5_0(raw) })

type Endpoint6_0Request = Parameters<RawClient["server.model"]["model.list"]>[0]
type Endpoint6_0Input = { readonly location?: Endpoint6_0Request["query"]["location"] }
const Endpoint6_0 = (raw: RawClient["server.model"]) => (input?: Endpoint6_0Input) =>
  raw["model.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup6 = (raw: RawClient["server.model"]) => ({ list: Endpoint6_0(raw) })

type Endpoint7_0Request = Parameters<RawClient["server.provider"]["provider.list"]>[0]
type Endpoint7_0Input = { readonly location?: Endpoint7_0Request["query"]["location"] }
const Endpoint7_0 = (raw: RawClient["server.provider"]) => (input?: Endpoint7_0Input) =>
  raw["provider.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint7_1Request = Parameters<RawClient["server.provider"]["provider.get"]>[0]
type Endpoint7_1Input = {
  readonly providerID: Endpoint7_1Request["params"]["providerID"]
  readonly location?: Endpoint7_1Request["query"]["location"]
}
const Endpoint7_1 = (raw: RawClient["server.provider"]) => (input: Endpoint7_1Input) =>
  raw["provider.get"]({ params: { providerID: input["providerID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup7 = (raw: RawClient["server.provider"]) => ({ list: Endpoint7_0(raw), get: Endpoint7_1(raw) })

type Endpoint8_0Request = Parameters<RawClient["server.integration"]["integration.list"]>[0]
type Endpoint8_0Input = { readonly location?: Endpoint8_0Request["query"]["location"] }
const Endpoint8_0 = (raw: RawClient["server.integration"]) => (input?: Endpoint8_0Input) =>
  raw["integration.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint8_1Request = Parameters<RawClient["server.integration"]["integration.get"]>[0]
type Endpoint8_1Input = {
  readonly integrationID: Endpoint8_1Request["params"]["integrationID"]
  readonly location?: Endpoint8_1Request["query"]["location"]
}
const Endpoint8_1 = (raw: RawClient["server.integration"]) => (input: Endpoint8_1Input) =>
  raw["integration.get"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_2Request = Parameters<RawClient["server.integration"]["integration.connect.key"]>[0]
type Endpoint8_2Input = {
  readonly integrationID: Endpoint8_2Request["params"]["integrationID"]
  readonly location?: Endpoint8_2Request["query"]["location"]
  readonly key: Endpoint8_2Request["payload"]["key"]
  readonly label?: Endpoint8_2Request["payload"]["label"]
}
const Endpoint8_2 = (raw: RawClient["server.integration"]) => (input: Endpoint8_2Input) =>
  raw["integration.connect.key"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { key: input["key"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_3Request = Parameters<RawClient["server.integration"]["integration.connect.oauth"]>[0]
type Endpoint8_3Input = {
  readonly integrationID: Endpoint8_3Request["params"]["integrationID"]
  readonly location?: Endpoint8_3Request["query"]["location"]
  readonly methodID: Endpoint8_3Request["payload"]["methodID"]
  readonly inputs: Endpoint8_3Request["payload"]["inputs"]
  readonly label?: Endpoint8_3Request["payload"]["label"]
}
const Endpoint8_3 = (raw: RawClient["server.integration"]) => (input: Endpoint8_3Input) =>
  raw["integration.connect.oauth"]({
    params: { integrationID: input["integrationID"] },
    query: { location: input["location"] },
    payload: { methodID: input["methodID"], inputs: input["inputs"], label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_4Request = Parameters<RawClient["server.integration"]["integration.attempt.status"]>[0]
type Endpoint8_4Input = {
  readonly attemptID: Endpoint8_4Request["params"]["attemptID"]
  readonly location?: Endpoint8_4Request["query"]["location"]
}
const Endpoint8_4 = (raw: RawClient["server.integration"]) => (input: Endpoint8_4Input) =>
  raw["integration.attempt.status"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_5Request = Parameters<RawClient["server.integration"]["integration.attempt.complete"]>[0]
type Endpoint8_5Input = {
  readonly attemptID: Endpoint8_5Request["params"]["attemptID"]
  readonly location?: Endpoint8_5Request["query"]["location"]
  readonly code?: Endpoint8_5Request["payload"]["code"]
}
const Endpoint8_5 = (raw: RawClient["server.integration"]) => (input: Endpoint8_5Input) =>
  raw["integration.attempt.complete"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
    payload: { code: input["code"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint8_6Request = Parameters<RawClient["server.integration"]["integration.attempt.cancel"]>[0]
type Endpoint8_6Input = {
  readonly attemptID: Endpoint8_6Request["params"]["attemptID"]
  readonly location?: Endpoint8_6Request["query"]["location"]
}
const Endpoint8_6 = (raw: RawClient["server.integration"]) => (input: Endpoint8_6Input) =>
  raw["integration.attempt.cancel"]({
    params: { attemptID: input["attemptID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup8 = (raw: RawClient["server.integration"]) => ({
  list: Endpoint8_0(raw),
  get: Endpoint8_1(raw),
  connectKey: Endpoint8_2(raw),
  connectOauth: Endpoint8_3(raw),
  attemptStatus: Endpoint8_4(raw),
  attemptComplete: Endpoint8_5(raw),
  attemptCancel: Endpoint8_6(raw),
})

type Endpoint9_0Request = Parameters<RawClient["server.credential"]["credential.update"]>[0]
type Endpoint9_0Input = {
  readonly credentialID: Endpoint9_0Request["params"]["credentialID"]
  readonly location?: Endpoint9_0Request["query"]["location"]
  readonly label: Endpoint9_0Request["payload"]["label"]
}
const Endpoint9_0 = (raw: RawClient["server.credential"]) => (input: Endpoint9_0Input) =>
  raw["credential.update"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
    payload: { label: input["label"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint9_1Request = Parameters<RawClient["server.credential"]["credential.remove"]>[0]
type Endpoint9_1Input = {
  readonly credentialID: Endpoint9_1Request["params"]["credentialID"]
  readonly location?: Endpoint9_1Request["query"]["location"]
}
const Endpoint9_1 = (raw: RawClient["server.credential"]) => (input: Endpoint9_1Input) =>
  raw["credential.remove"]({
    params: { credentialID: input["credentialID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup9 = (raw: RawClient["server.credential"]) => ({ update: Endpoint9_0(raw), remove: Endpoint9_1(raw) })

type Endpoint10_0Request = Parameters<RawClient["server.permission"]["permission.request.list"]>[0]
type Endpoint10_0Input = { readonly location?: Endpoint10_0Request["query"]["location"] }
const Endpoint10_0 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_0Input) =>
  raw["permission.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_1Request = Parameters<RawClient["server.permission"]["permission.saved.list"]>[0]
type Endpoint10_1Input = { readonly projectID?: Endpoint10_1Request["query"]["projectID"] }
const Endpoint10_1 = (raw: RawClient["server.permission"]) => (input?: Endpoint10_1Input) =>
  raw["permission.saved.list"]({ query: { projectID: input?.["projectID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_2Request = Parameters<RawClient["server.permission"]["permission.saved.remove"]>[0]
type Endpoint10_2Input = { readonly id: Endpoint10_2Request["params"]["id"] }
const Endpoint10_2 = (raw: RawClient["server.permission"]) => (input: Endpoint10_2Input) =>
  raw["permission.saved.remove"]({ params: { id: input["id"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint10_3Request = Parameters<RawClient["server.permission"]["session.permission.create"]>[0]
type Endpoint10_3Input = {
  readonly sessionID: Endpoint10_3Request["params"]["sessionID"]
  readonly id?: Endpoint10_3Request["payload"]["id"]
  readonly action: Endpoint10_3Request["payload"]["action"]
  readonly resources: Endpoint10_3Request["payload"]["resources"]
  readonly save?: Endpoint10_3Request["payload"]["save"]
  readonly metadata?: Endpoint10_3Request["payload"]["metadata"]
  readonly source?: Endpoint10_3Request["payload"]["source"]
  readonly agent?: Endpoint10_3Request["payload"]["agent"]
}
const Endpoint10_3 = (raw: RawClient["server.permission"]) => (input: Endpoint10_3Input) =>
  raw["session.permission.create"]({
    params: { sessionID: input["sessionID"] },
    payload: {
      id: input["id"],
      action: input["action"],
      resources: input["resources"],
      save: input["save"],
      metadata: input["metadata"],
      source: input["source"],
      agent: input["agent"],
    },
  }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_4Request = Parameters<RawClient["server.permission"]["session.permission.list"]>[0]
type Endpoint10_4Input = { readonly sessionID: Endpoint10_4Request["params"]["sessionID"] }
const Endpoint10_4 = (raw: RawClient["server.permission"]) => (input: Endpoint10_4Input) =>
  raw["session.permission.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_5Request = Parameters<RawClient["server.permission"]["session.permission.get"]>[0]
type Endpoint10_5Input = {
  readonly sessionID: Endpoint10_5Request["params"]["sessionID"]
  readonly requestID: Endpoint10_5Request["params"]["requestID"]
}
const Endpoint10_5 = (raw: RawClient["server.permission"]) => (input: Endpoint10_5Input) =>
  raw["session.permission.get"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint10_6Request = Parameters<RawClient["server.permission"]["session.permission.reply"]>[0]
type Endpoint10_6Input = {
  readonly sessionID: Endpoint10_6Request["params"]["sessionID"]
  readonly requestID: Endpoint10_6Request["params"]["requestID"]
  readonly reply: Endpoint10_6Request["payload"]["reply"]
  readonly message?: Endpoint10_6Request["payload"]["message"]
}
const Endpoint10_6 = (raw: RawClient["server.permission"]) => (input: Endpoint10_6Input) =>
  raw["session.permission.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { reply: input["reply"], message: input["message"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup10 = (raw: RawClient["server.permission"]) => ({
  listRequests: Endpoint10_0(raw),
  listSaved: Endpoint10_1(raw),
  removeSaved: Endpoint10_2(raw),
  create: Endpoint10_3(raw),
  list: Endpoint10_4(raw),
  get: Endpoint10_5(raw),
  reply: Endpoint10_6(raw),
})

type Endpoint11_0Request = Parameters<RawClient["server.fs"]["fs.list"]>[0]
type Endpoint11_0Input = {
  readonly location?: Endpoint11_0Request["query"]["location"]
  readonly path?: Endpoint11_0Request["query"]["path"]
}
const Endpoint11_0 = (raw: RawClient["server.fs"]) => (input?: Endpoint11_0Input) =>
  raw["fs.list"]({ query: { location: input?.["location"], path: input?.["path"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint11_1Request = Parameters<RawClient["server.fs"]["fs.find"]>[0]
type Endpoint11_1Input = {
  readonly location?: Endpoint11_1Request["query"]["location"]
  readonly query: Endpoint11_1Request["query"]["query"]
  readonly type?: Endpoint11_1Request["query"]["type"]
  readonly limit?: Endpoint11_1Request["query"]["limit"]
}
const Endpoint11_1 = (raw: RawClient["server.fs"]) => (input: Endpoint11_1Input) =>
  raw["fs.find"]({
    query: { location: input["location"], query: input["query"], type: input["type"], limit: input["limit"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup11 = (raw: RawClient["server.fs"]) => ({ list: Endpoint11_0(raw), find: Endpoint11_1(raw) })

type Endpoint12_0Request = Parameters<RawClient["server.command"]["command.list"]>[0]
type Endpoint12_0Input = { readonly location?: Endpoint12_0Request["query"]["location"] }
const Endpoint12_0 = (raw: RawClient["server.command"]) => (input?: Endpoint12_0Input) =>
  raw["command.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup12 = (raw: RawClient["server.command"]) => ({ list: Endpoint12_0(raw) })

type Endpoint13_0Request = Parameters<RawClient["server.skill"]["skill.list"]>[0]
type Endpoint13_0Input = { readonly location?: Endpoint13_0Request["query"]["location"] }
const Endpoint13_0 = (raw: RawClient["server.skill"]) => (input?: Endpoint13_0Input) =>
  raw["skill.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup13 = (raw: RawClient["server.skill"]) => ({ list: Endpoint13_0(raw) })

const Endpoint14_0 = (raw: RawClient["server.event"]) => () =>
  Stream.unwrap(
    raw["event.subscribe"]({}).pipe(
      Effect.mapError(mapClientError),
      Effect.map((stream) => stream.pipe(Stream.mapError(mapClientError))),
    ),
  )

const adaptGroup14 = (raw: RawClient["server.event"]) => ({ subscribe: Endpoint14_0(raw) })

type Endpoint15_0Request = Parameters<RawClient["server.pty"]["pty.list"]>[0]
type Endpoint15_0Input = { readonly location?: Endpoint15_0Request["query"]["location"] }
const Endpoint15_0 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_0Input) =>
  raw["pty.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint15_1Request = Parameters<RawClient["server.pty"]["pty.create"]>[0]
type Endpoint15_1Input = {
  readonly location?: Endpoint15_1Request["query"]["location"]
  readonly command?: Endpoint15_1Request["payload"]["command"]
  readonly args?: Endpoint15_1Request["payload"]["args"]
  readonly cwd?: Endpoint15_1Request["payload"]["cwd"]
  readonly title?: Endpoint15_1Request["payload"]["title"]
  readonly env?: Endpoint15_1Request["payload"]["env"]
}
const Endpoint15_1 = (raw: RawClient["server.pty"]) => (input?: Endpoint15_1Input) =>
  raw["pty.create"]({
    query: { location: input?.["location"] },
    payload: {
      command: input?.["command"],
      args: input?.["args"],
      cwd: input?.["cwd"],
      title: input?.["title"],
      env: input?.["env"],
    },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_2Request = Parameters<RawClient["server.pty"]["pty.get"]>[0]
type Endpoint15_2Input = {
  readonly ptyID: Endpoint15_2Request["params"]["ptyID"]
  readonly location?: Endpoint15_2Request["query"]["location"]
}
const Endpoint15_2 = (raw: RawClient["server.pty"]) => (input: Endpoint15_2Input) =>
  raw["pty.get"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

type Endpoint15_3Request = Parameters<RawClient["server.pty"]["pty.update"]>[0]
type Endpoint15_3Input = {
  readonly ptyID: Endpoint15_3Request["params"]["ptyID"]
  readonly location?: Endpoint15_3Request["query"]["location"]
  readonly title?: Endpoint15_3Request["payload"]["title"]
  readonly size?: Endpoint15_3Request["payload"]["size"]
}
const Endpoint15_3 = (raw: RawClient["server.pty"]) => (input: Endpoint15_3Input) =>
  raw["pty.update"]({
    params: { ptyID: input["ptyID"] },
    query: { location: input["location"] },
    payload: { title: input["title"], size: input["size"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint15_4Request = Parameters<RawClient["server.pty"]["pty.remove"]>[0]
type Endpoint15_4Input = {
  readonly ptyID: Endpoint15_4Request["params"]["ptyID"]
  readonly location?: Endpoint15_4Request["query"]["location"]
}
const Endpoint15_4 = (raw: RawClient["server.pty"]) => (input: Endpoint15_4Input) =>
  raw["pty.remove"]({ params: { ptyID: input["ptyID"] }, query: { location: input["location"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup15 = (raw: RawClient["server.pty"]) => ({
  list: Endpoint15_0(raw),
  create: Endpoint15_1(raw),
  get: Endpoint15_2(raw),
  update: Endpoint15_3(raw),
  remove: Endpoint15_4(raw),
})

type Endpoint16_0Request = Parameters<RawClient["server.question"]["question.request.list"]>[0]
type Endpoint16_0Input = { readonly location?: Endpoint16_0Request["query"]["location"] }
const Endpoint16_0 = (raw: RawClient["server.question"]) => (input?: Endpoint16_0Input) =>
  raw["question.request.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

type Endpoint16_1Request = Parameters<RawClient["server.question"]["session.question.list"]>[0]
type Endpoint16_1Input = { readonly sessionID: Endpoint16_1Request["params"]["sessionID"] }
const Endpoint16_1 = (raw: RawClient["server.question"]) => (input: Endpoint16_1Input) =>
  raw["session.question.list"]({ params: { sessionID: input["sessionID"] } }).pipe(
    Effect.mapError(mapClientError),
    Effect.map((value) => value.data),
  )

type Endpoint16_2Request = Parameters<RawClient["server.question"]["session.question.reply"]>[0]
type Endpoint16_2Input = {
  readonly sessionID: Endpoint16_2Request["params"]["sessionID"]
  readonly requestID: Endpoint16_2Request["params"]["requestID"]
  readonly answers: Endpoint16_2Request["payload"]["answers"]
}
const Endpoint16_2 = (raw: RawClient["server.question"]) => (input: Endpoint16_2Input) =>
  raw["session.question.reply"]({
    params: { sessionID: input["sessionID"], requestID: input["requestID"] },
    payload: { answers: input["answers"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint16_3Request = Parameters<RawClient["server.question"]["session.question.reject"]>[0]
type Endpoint16_3Input = {
  readonly sessionID: Endpoint16_3Request["params"]["sessionID"]
  readonly requestID: Endpoint16_3Request["params"]["requestID"]
}
const Endpoint16_3 = (raw: RawClient["server.question"]) => (input: Endpoint16_3Input) =>
  raw["session.question.reject"]({ params: { sessionID: input["sessionID"], requestID: input["requestID"] } }).pipe(
    Effect.mapError(mapClientError),
  )

const adaptGroup16 = (raw: RawClient["server.question"]) => ({
  listRequests: Endpoint16_0(raw),
  list: Endpoint16_1(raw),
  reply: Endpoint16_2(raw),
  reject: Endpoint16_3(raw),
})

type Endpoint17_0Request = Parameters<RawClient["server.reference"]["reference.list"]>[0]
type Endpoint17_0Input = { readonly location?: Endpoint17_0Request["query"]["location"] }
const Endpoint17_0 = (raw: RawClient["server.reference"]) => (input?: Endpoint17_0Input) =>
  raw["reference.list"]({ query: { location: input?.["location"] } }).pipe(Effect.mapError(mapClientError))

const adaptGroup17 = (raw: RawClient["server.reference"]) => ({ list: Endpoint17_0(raw) })

type Endpoint18_0Request = Parameters<RawClient["server.projectCopy"]["projectCopy.create"]>[0]
type Endpoint18_0Input = {
  readonly projectID: Endpoint18_0Request["params"]["projectID"]
  readonly location?: Endpoint18_0Request["query"]["location"]
  readonly strategy: Endpoint18_0Request["payload"]["strategy"]
  readonly directory: Endpoint18_0Request["payload"]["directory"]
  readonly name?: Endpoint18_0Request["payload"]["name"]
}
const Endpoint18_0 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_0Input) =>
  raw["projectCopy.create"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { strategy: input["strategy"], directory: input["directory"], name: input["name"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_1Request = Parameters<RawClient["server.projectCopy"]["projectCopy.remove"]>[0]
type Endpoint18_1Input = {
  readonly projectID: Endpoint18_1Request["params"]["projectID"]
  readonly location?: Endpoint18_1Request["query"]["location"]
  readonly directory: Endpoint18_1Request["payload"]["directory"]
  readonly force: Endpoint18_1Request["payload"]["force"]
}
const Endpoint18_1 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_1Input) =>
  raw["projectCopy.remove"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
    payload: { directory: input["directory"], force: input["force"] },
  }).pipe(Effect.mapError(mapClientError))

type Endpoint18_2Request = Parameters<RawClient["server.projectCopy"]["projectCopy.refresh"]>[0]
type Endpoint18_2Input = {
  readonly projectID: Endpoint18_2Request["params"]["projectID"]
  readonly location?: Endpoint18_2Request["query"]["location"]
}
const Endpoint18_2 = (raw: RawClient["server.projectCopy"]) => (input: Endpoint18_2Input) =>
  raw["projectCopy.refresh"]({
    params: { projectID: input["projectID"] },
    query: { location: input["location"] },
  }).pipe(Effect.mapError(mapClientError))

const adaptGroup18 = (raw: RawClient["server.projectCopy"]) => ({
  create: Endpoint18_0(raw),
  remove: Endpoint18_1(raw),
  refresh: Endpoint18_2(raw),
})

const adaptClient = (raw: RawClient) => ({
  health: adaptGroup0(raw["server.health"]),
  issueWatchers: adaptGroup1(raw["server.issueWatcher"]),
  location: adaptGroup2(raw["server.location"]),
  agents: adaptGroup3(raw["server.agent"]),
  sessions: adaptGroup4(raw["server.session"]),
  messages: adaptGroup5(raw["server.message"]),
  models: adaptGroup6(raw["server.model"]),
  providers: adaptGroup7(raw["server.provider"]),
  integrations: adaptGroup8(raw["server.integration"]),
  credentials: adaptGroup9(raw["server.credential"]),
  permissions: adaptGroup10(raw["server.permission"]),
  files: adaptGroup11(raw["server.fs"]),
  commands: adaptGroup12(raw["server.command"]),
  skills: adaptGroup13(raw["server.skill"]),
  events: adaptGroup14(raw["server.event"]),
  ptys: adaptGroup15(raw["server.pty"]),
  questions: adaptGroup16(raw["server.question"]),
  references: adaptGroup17(raw["server.reference"]),
  projectCopies: adaptGroup18(raw["server.projectCopy"]),
})

export const make = (options?: { readonly baseUrl?: URL | string }) =>
  HttpApiClient.make(ClientApi, options).pipe(Effect.map(adaptClient))
